import { NextResponse } from "next/server";

export async function POST() {
    try {
        const data = {
            "message": "Contact Created",
            "status": "success"
        }

        return NextResponse.json(data);
    } catch (error) {
        return NextResponse.json(
            { error: (error as Error).message || "An unexpected error occurred" },
            { status: 500 }
        );
    }
}

export async function GET() {
    try {
        const data = {
            "data": [
                {
                    "id": 20,
                    "profilePictureUrl": null,
                    "firstName": "Aaaty",
                    "surname": "Aabrun",
                    "middleName": null,
                    "salutation": null,
                    "postNominal": null,
                    "preferredName": " Aabrun, Aaaty ",
                    "fullName": " Aabrun, Aaaty ",
                    "emailAddress": "abrun135@gmail.com",
                    "mobileNumber": null,
                    "membershipNumber": "6",
                    "membershipStatus": "Current",
                    "membershipType": {
                        "id": 2,
                        "name": "Ordinary Membership",
                        "description": "<div>Ordinary Membership</div>",
                        "customerType": "",
                        "displayOrder": 10,
                        "renewalType": "",
                        "renewalDay": 1,
                        "renewalMonth": 1,
                        "amount": "50.0000",
                        "productCode": "SB-1-2"
                    },
                    "contactStatus": 0,
                    "description": null,
                    "externalIdentifier": null,
                    "importReference": null,
                    "birthDate": null,
                    "dateRegistered": "2024-11-29T10:06:55.000000Z",
                    "dateJoined": "2024-11-29T00:00:00.000000Z",
                    "createdAt": "2024-11-29T10:06:55.000000Z",
                    "updatedAt": "2024-11-29T10:07:34.000000Z",
                    "businessUnit": {
                        "id": 9,
                        "name": "LEICESTERSHIRE",
                        "parentId": 1,
                        "description": null,
                        "groupId": 2,
                        "createdAt": "2024-11-29T09:42:15.000000Z",
                        "updatedAt": "2024-11-29T09:42:15.000000Z"
                    },
                    "contactCustom536": null
                },
                {
                    "id": 2,
                    "profilePictureUrl": null,
                    "firstName": "Alyson",
                    "surname": "Williamson",
                    "middleName": null,
                    "salutation": null,
                    "postNominal": null,
                    "preferredName": " Williamson, Alyson ",
                    "fullName": " Williamson, Alyson ",
                    "emailAddress": "Clinton_Bogan@yahoo.com",
                    "mobileNumber": "1-574-282-3563 x3589",
                    "membershipNumber": "8",
                    "membershipStatus": "Current",
                    "membershipType": {
                        "id": 4,
                        "name": "All Membership",
                        "description": "<div>All Membership</div>",
                        "customerType": "",
                        "displayOrder": 30,
                        "renewalType": "",
                        "renewalDay": 1,
                        "renewalMonth": 1,
                        "amount": "50.0000",
                        "productCode": "SB-1-4"
                    },
                    "contactStatus": 0,
                    "description": null,
                    "externalIdentifier": null,
                    "importReference": null,
                    "birthDate": null,
                    "dateRegistered": "2024-11-29T09:43:30.000000Z",
                    "dateJoined": "2024-11-29T00:00:00.000000Z",
                    "createdAt": "2024-11-29T09:43:30.000000Z",
                    "updatedAt": "2024-11-29T10:13:44.000000Z",
                    "businessUnit": {
                        "id": 1,
                        "name": "Mobile App",
                        "parentId": null,
                        "description": null,
                        "groupId": 1,
                        "createdAt": "2024-11-28T16:29:31.000000Z",
                        "updatedAt": "2024-11-28T16:29:31.000000Z"
                    },
                    "contactCustom536": null
                },
                {
                    "id": 10,
                    "profilePictureUrl": null,
                    "firstName": "Christopher",
                    "surname": "Abeneze",
                    "middleName": null,
                    "salutation": null,
                    "postNominal": null,
                    "preferredName": " Abeneze, Christopher ",
                    "fullName": " Abeneze, Christopher ",
                    "emailAddress": "chris.eneze@gmail.com",
                    "mobileNumber": null,
                    "membershipNumber": null,
                    "membershipStatus": "Non member",
                    "membershipType": null,
                    "contactStatus": 0,
                    "description": null,
                    "externalIdentifier": null,
                    "importReference": null,
                    "birthDate": null,
                    "dateRegistered": "2024-11-29T09:51:28.000000Z",
                    "dateJoined": null,
                    "createdAt": "2024-11-29T09:51:28.000000Z",
                    "updatedAt": "2024-11-29T09:51:35.000000Z",
                    "businessUnit": {
                        "id": 9,
                        "name": "LEICESTERSHIRE",
                        "parentId": 1,
                        "description": null,
                        "groupId": 2,
                        "createdAt": "2024-11-29T09:42:15.000000Z",
                        "updatedAt": "2024-11-29T09:42:15.000000Z"
                    },
                    "contactCustom536": null
                },
                {
                    "id": 5,
                    "profilePictureUrl": null,
                    "firstName": "Danielle",
                    "surname": "Hilpert",
                    "middleName": null,
                    "salutation": null,
                    "postNominal": null,
                    "preferredName": " Hilpert, Danielle ",
                    "fullName": " Hilpert, Danielle ",
                    "emailAddress": "Judy_Marks43@hotmail.com",
                    "mobileNumber": "(984) 219-9378 x0249",
                    "membershipNumber": null,
                    "membershipStatus": "Non member",
                    "membershipType": null,
                    "contactStatus": 0,
                    "description": null,
                    "externalIdentifier": null,
                    "importReference": null,
                    "birthDate": null,
                    "dateRegistered": "2024-11-29T09:45:16.000000Z",
                    "dateJoined": null,
                    "createdAt": "2024-11-29T09:45:16.000000Z",
                    "updatedAt": "2024-11-29T09:45:16.000000Z",
                    "businessUnit": {
                        "id": 1,
                        "name": "Mobile App",
                        "parentId": null,
                        "description": null,
                        "groupId": 1,
                        "createdAt": "2024-11-28T16:29:31.000000Z",
                        "updatedAt": "2024-11-28T16:29:31.000000Z"
                    },
                    "contactCustom536": null
                },
                {
                    "id": 12,
                    "profilePictureUrl": null,
                    "firstName": "Dave",
                    "surname": "Coll",
                    "middleName": "Gray",
                    "salutation": "Mr",
                    "postNominal": null,
                    "preferredName": "Mr Coll, Dave Gray",
                    "fullName": "Mr Coll, Dave Gray",
                    "emailAddress": "37@gmail.com",
                    "mobileNumber": null,
                    "membershipNumber": null,
                    "membershipStatus": "Non member",
                    "membershipType": null,
                    "contactStatus": 0,
                    "description": null,
                    "externalIdentifier": null,
                    "importReference": null,
                    "birthDate": null,
                    "dateRegistered": "2024-11-29T09:52:42.000000Z",
                    "dateJoined": null,
                    "createdAt": "2024-11-29T09:52:42.000000Z",
                    "updatedAt": "2024-11-29T09:52:47.000000Z",
                    "businessUnit": {
                        "id": 1,
                        "name": "Mobile App",
                        "parentId": null,
                        "description": null,
                        "groupId": 1,
                        "createdAt": "2024-11-28T16:29:31.000000Z",
                        "updatedAt": "2024-11-28T16:29:31.000000Z"
                    },
                    "contactCustom536": null
                },
                {
                    "id": 24,
                    "profilePictureUrl": null,
                    "firstName": "Gloria",
                    "surname": "Anni",
                    "middleName": null,
                    "salutation": "Mrs",
                    "postNominal": null,
                    "preferredName": "Mrs Anni, Gloria ",
                    "fullName": "Mrs Anni, Gloria ",
                    "emailAddress": "glorianni@yopmail.com",
                    "mobileNumber": null,
                    "membershipNumber": "7",
                    "membershipStatus": "Current",
                    "membershipType": {
                        "id": 4,
                        "name": "All Membership",
                        "description": "<div>All Membership</div>",
                        "customerType": "",
                        "displayOrder": 30,
                        "renewalType": "",
                        "renewalDay": 1,
                        "renewalMonth": 1,
                        "amount": "50.0000",
                        "productCode": "SB-1-4"
                    },
                    "contactStatus": 0,
                    "description": null,
                    "externalIdentifier": null,
                    "importReference": null,
                    "birthDate": null,
                    "dateRegistered": "2024-11-29T10:12:39.000000Z",
                    "dateJoined": "2024-11-29T00:00:00.000000Z",
                    "createdAt": "2024-11-29T10:12:39.000000Z",
                    "updatedAt": "2024-11-29T10:12:57.000000Z",
                    "businessUnit": {
                        "id": 1,
                        "name": "Mobile App",
                        "parentId": null,
                        "description": null,
                        "groupId": 1,
                        "createdAt": "2024-11-28T16:29:31.000000Z",
                        "updatedAt": "2024-11-28T16:29:31.000000Z"
                    },
                    "contactCustom536": null
                },
                {
                    "id": 17,
                    "profilePictureUrl": null,
                    "firstName": "Godson",
                    "surname": "Phil",
                    "middleName": null,
                    "salutation": null,
                    "postNominal": null,
                    "preferredName": " Phil, Godson ",
                    "fullName": " Phil, Godson ",
                    "emailAddress": "phil@yopmail.com",
                    "mobileNumber": null,
                    "membershipNumber": null,
                    "membershipStatus": "Non member",
                    "membershipType": null,
                    "contactStatus": 0,
                    "description": null,
                    "externalIdentifier": null,
                    "importReference": null,
                    "birthDate": null,
                    "dateRegistered": "2024-11-29T10:04:00.000000Z",
                    "dateJoined": null,
                    "createdAt": "2024-11-29T10:04:00.000000Z",
                    "updatedAt": "2024-11-29T10:04:00.000000Z",
                    "businessUnit": {
                        "id": 1,
                        "name": "Mobile App",
                        "parentId": null,
                        "description": null,
                        "groupId": 1,
                        "createdAt": "2024-11-28T16:29:31.000000Z",
                        "updatedAt": "2024-11-28T16:29:31.000000Z"
                    },
                    "contactCustom536": "This should persist"
                },
                {
                    "id": 8,
                    "profilePictureUrl": null,
                    "firstName": "Havert",
                    "surname": "Goodwins",
                    "middleName": null,
                    "salutation": "Mr",
                    "postNominal": null,
                    "preferredName": "Mr Goodwins, Havert ",
                    "fullName": "Mr Goodwins, Havert ",
                    "emailAddress": "hebertwim@yopmail.com",
                    "mobileNumber": null,
                    "membershipNumber": "3",
                    "membershipStatus": "Lapsed",
                    "membershipType": {
                        "id": 3,
                        "name": "Overseas Associate",
                        "description": "<div>Overseas Associate</div>",
                        "customerType": "",
                        "displayOrder": 20,
                        "renewalType": "",
                        "renewalDay": 1,
                        "renewalMonth": 1,
                        "amount": "50.0000",
                        "productCode": "SB-1-3"
                    },
                    "contactStatus": 0,
                    "description": null,
                    "externalIdentifier": null,
                    "importReference": null,
                    "birthDate": null,
                    "dateRegistered": "2024-11-29T09:50:06.000000Z",
                    "dateJoined": "2024-11-27T00:00:00.000000Z",
                    "createdAt": "2024-11-29T09:50:06.000000Z",
                    "updatedAt": "2024-11-29T09:50:11.000000Z",
                    "businessUnit": {
                        "id": 1,
                        "name": "Mobile App",
                        "parentId": null,
                        "description": null,
                        "groupId": 1,
                        "createdAt": "2024-11-28T16:29:31.000000Z",
                        "updatedAt": "2024-11-28T16:29:31.000000Z"
                    },
                    "contactCustom536": null
                },
                {
                    "id": 27,
                    "profilePictureUrl": null,
                    "firstName": "Hillary",
                    "surname": "Clinton",
                    "middleName": null,
                    "salutation": null,
                    "postNominal": null,
                    "preferredName": " Clinton, Hillary ",
                    "fullName": " Clinton, Hillary ",
                    "emailAddress": "clinhill@gmail.com",
                    "mobileNumber": null,
                    "membershipNumber": "735",
                    "membershipStatus": "Current",
                    "membershipType": {
                        "id": 1,
                        "name": "Associate Membership",
                        "description": "<div>Associate Membership</div>",
                        "customerType": "",
                        "displayOrder": 0,
                        "renewalType": "",
                        "renewalDay": 1,
                        "renewalMonth": 1,
                        "amount": "50.0000",
                        "productCode": "SB-1-1"
                    },
                    "contactStatus": 0,
                    "description": null,
                    "externalIdentifier": null,
                    "importReference": null,
                    "birthDate": null,
                    "dateRegistered": "2024-11-29T10:17:02.000000Z",
                    "dateJoined": "2024-11-29T00:00:00.000000Z",
                    "createdAt": "2024-11-29T10:17:02.000000Z",
                    "updatedAt": "2024-11-29T10:17:17.000000Z",
                    "businessUnit": {
                        "id": 1,
                        "name": "Mobile App",
                        "parentId": null,
                        "description": null,
                        "groupId": 1,
                        "createdAt": "2024-11-28T16:29:31.000000Z",
                        "updatedAt": "2024-11-28T16:29:31.000000Z"
                    },
                    "contactCustom536": null
                },
                {
                    "id": 16,
                    "profilePictureUrl": null,
                    "firstName": "Julian",
                    "surname": "Alvares",
                    "middleName": null,
                    "salutation": null,
                    "postNominal": null,
                    "preferredName": " Alvares, Julian ",
                    "fullName": " Alvares, Julian ",
                    "emailAddress": "julian.alvares@gmail.com",
                    "mobileNumber": null,
                    "membershipNumber": null,
                    "membershipStatus": "Non member",
                    "membershipType": null,
                    "contactStatus": 0,
                    "description": null,
                    "externalIdentifier": null,
                    "importReference": null,
                    "birthDate": null,
                    "dateRegistered": "2024-11-29T10:03:08.000000Z",
                    "dateJoined": null,
                    "createdAt": "2024-11-29T10:03:08.000000Z",
                    "updatedAt": "2024-11-29T10:03:08.000000Z",
                    "businessUnit": {
                        "id": 1,
                        "name": "Mobile App",
                        "parentId": null,
                        "description": null,
                        "groupId": 1,
                        "createdAt": "2024-11-28T16:29:31.000000Z",
                        "updatedAt": "2024-11-28T16:29:31.000000Z"
                    },
                    "contactCustom536": null
                },
                {
                    "id": 1,
                    "profilePictureUrl": null,
                    "firstName": "Kingsley",
                    "surname": "Mount",
                    "middleName": "Noni",
                    "salutation": null,
                    "postNominal": null,
                    "preferredName": "Mount, Kingsley",
                    "fullName": " Mount, Kingsley Noni",
                    "emailAddress": "kingsley@yopmail.com",
                    "mobileNumber": null,
                    "membershipNumber": null,
                    "membershipStatus": "Non member",
                    "membershipType": null,
                    "contactStatus": 0,
                    "description": null,
                    "externalIdentifier": null,
                    "importReference": null,
                    "birthDate": null,
                    "dateRegistered": "2024-11-29T09:16:28.000000Z",
                    "dateJoined": null,
                    "createdAt": "2024-11-29T09:16:28.000000Z",
                    "updatedAt": "2024-11-29T09:18:14.000000Z",
                    "businessUnit": {
                        "id": 1,
                        "name": "Mobile App",
                        "parentId": null,
                        "description": null,
                        "groupId": 1,
                        "createdAt": "2024-11-28T16:29:31.000000Z",
                        "updatedAt": "2024-11-28T16:29:31.000000Z"
                    },
                    "contactCustom536": null
                },
                {
                    "id": 25,
                    "profilePictureUrl": null,
                    "firstName": "Mark",
                    "surname": "Suchbo",
                    "middleName": null,
                    "salutation": "Dr",
                    "postNominal": null,
                    "preferredName": "Dr Suchbo, Mark ",
                    "fullName": "Dr Suchbo, Mark ",
                    "emailAddress": "mark@gmail.com",
                    "mobileNumber": null,
                    "membershipNumber": "9",
                    "membershipStatus": "Current",
                    "membershipType": {
                        "id": 4,
                        "name": "All Membership",
                        "description": "<div>All Membership</div>",
                        "customerType": "",
                        "displayOrder": 30,
                        "renewalType": "",
                        "renewalDay": 1,
                        "renewalMonth": 1,
                        "amount": "50.0000",
                        "productCode": "SB-1-4"
                    },
                    "contactStatus": 0,
                    "description": null,
                    "externalIdentifier": null,
                    "importReference": null,
                    "birthDate": null,
                    "dateRegistered": "2024-11-29T10:14:12.000000Z",
                    "dateJoined": "2024-11-29T00:00:00.000000Z",
                    "createdAt": "2024-11-29T10:14:12.000000Z",
                    "updatedAt": "2024-11-29T10:14:36.000000Z",
                    "businessUnit": {
                        "id": 1,
                        "name": "Mobile App",
                        "parentId": null,
                        "description": null,
                        "groupId": 1,
                        "createdAt": "2024-11-28T16:29:31.000000Z",
                        "updatedAt": "2024-11-28T16:29:31.000000Z"
                    },
                    "contactCustom536": null
                },
                {
                    "id": 21,
                    "profilePictureUrl": null,
                    "firstName": "Marvelous",
                    "surname": "Okoren",
                    "middleName": null,
                    "salutation": null,
                    "postNominal": null,
                    "preferredName": " Okoren, Marvelous ",
                    "fullName": " Okoren, Marvelous ",
                    "emailAddress": "marve669@gmail.com",
                    "mobileNumber": "4465482938",
                    "membershipNumber": null,
                    "membershipStatus": "Non member",
                    "membershipType": null,
                    "contactStatus": 0,
                    "description": null,
                    "externalIdentifier": null,
                    "importReference": null,
                    "birthDate": null,
                    "dateRegistered": "2024-11-29T10:10:38.000000Z",
                    "dateJoined": null,
                    "createdAt": "2024-11-29T10:10:38.000000Z",
                    "updatedAt": "2024-11-29T10:10:38.000000Z",
                    "businessUnit": {
                        "id": 1,
                        "name": "Mobile App",
                        "parentId": null,
                        "description": null,
                        "groupId": 1,
                        "createdAt": "2024-11-28T16:29:31.000000Z",
                        "updatedAt": "2024-11-28T16:29:31.000000Z"
                    },
                    "contactCustom536": null
                },
                {
                    "id": 22,
                    "profilePictureUrl": null,
                    "firstName": "Marvelous",
                    "surname": "Okoren",
                    "middleName": null,
                    "salutation": null,
                    "postNominal": null,
                    "preferredName": " Okoren, Marvelous ",
                    "fullName": " Okoren, Marvelous ",
                    "emailAddress": "marve669@gmail.com",
                    "mobileNumber": "4465482938",
                    "membershipNumber": null,
                    "membershipStatus": "Non member",
                    "membershipType": null,
                    "contactStatus": 0,
                    "description": null,
                    "externalIdentifier": null,
                    "importReference": null,
                    "birthDate": null,
                    "dateRegistered": "2024-11-29T10:10:38.000000Z",
                    "dateJoined": null,
                    "createdAt": "2024-11-29T10:10:38.000000Z",
                    "updatedAt": "2024-11-29T10:10:38.000000Z",
                    "businessUnit": {
                        "id": 1,
                        "name": "Mobile App",
                        "parentId": null,
                        "description": null,
                        "groupId": 1,
                        "createdAt": "2024-11-28T16:29:31.000000Z",
                        "updatedAt": "2024-11-28T16:29:31.000000Z"
                    },
                    "contactCustom536": null
                },
                {
                    "id": 30,
                    "profilePictureUrl": null,
                    "firstName": "Matt",
                    "surname": "Fein",
                    "middleName": null,
                    "salutation": null,
                    "postNominal": null,
                    "preferredName": " Fein, Matt ",
                    "fullName": " Fein, Matt ",
                    "emailAddress": "matt@gmail.com",
                    "mobileNumber": null,
                    "membershipNumber": "739",
                    "membershipStatus": "Current",
                    "membershipType": {
                        "id": 4,
                        "name": "All Membership",
                        "description": "<div>All Membership</div>",
                        "customerType": "",
                        "displayOrder": 30,
                        "renewalType": "",
                        "renewalDay": 1,
                        "renewalMonth": 1,
                        "amount": "50.0000",
                        "productCode": "SB-1-4"
                    },
                    "contactStatus": 0,
                    "description": null,
                    "externalIdentifier": null,
                    "importReference": null,
                    "birthDate": null,
                    "dateRegistered": "2024-11-29T10:20:42.000000Z",
                    "dateJoined": "2024-11-29T00:00:00.000000Z",
                    "createdAt": "2024-11-29T10:20:42.000000Z",
                    "updatedAt": "2024-11-29T10:21:02.000000Z",
                    "businessUnit": {
                        "id": 1,
                        "name": "Mobile App",
                        "parentId": null,
                        "description": null,
                        "groupId": 1,
                        "createdAt": "2024-11-28T16:29:31.000000Z",
                        "updatedAt": "2024-11-28T16:29:31.000000Z"
                    },
                    "contactCustom536": null
                },
                {
                    "id": 9,
                    "profilePictureUrl": null,
                    "firstName": "Maya",
                    "surname": "Bijou",
                    "middleName": null,
                    "salutation": null,
                    "postNominal": null,
                    "preferredName": " Bijou, Maya ",
                    "fullName": " Bijou, Maya ",
                    "emailAddress": "maya@yopmail.com",
                    "mobileNumber": null,
                    "membershipNumber": "4",
                    "membershipStatus": "Current",
                    "membershipType": {
                        "id": 3,
                        "name": "Overseas Associate",
                        "description": "<div>Overseas Associate</div>",
                        "customerType": "",
                        "displayOrder": 20,
                        "renewalType": "",
                        "renewalDay": 1,
                        "renewalMonth": 1,
                        "amount": "50.0000",
                        "productCode": "SB-1-3"
                    },
                    "contactStatus": 0,
                    "description": null,
                    "externalIdentifier": null,
                    "importReference": null,
                    "birthDate": null,
                    "dateRegistered": "2024-11-29T09:50:53.000000Z",
                    "dateJoined": "2024-11-29T00:00:00.000000Z",
                    "createdAt": "2024-11-29T09:50:53.000000Z",
                    "updatedAt": "2024-11-29T09:51:06.000000Z",
                    "businessUnit": {
                        "id": 1,
                        "name": "Mobile App",
                        "parentId": null,
                        "description": null,
                        "groupId": 1,
                        "createdAt": "2024-11-28T16:29:31.000000Z",
                        "updatedAt": "2024-11-28T16:29:31.000000Z"
                    },
                    "contactCustom536": null
                },
                {
                    "id": 11,
                    "profilePictureUrl": null,
                    "firstName": "Nelson",
                    "surname": "Akujiobi",
                    "middleName": "Sito",
                    "salutation": "Mr",
                    "postNominal": "Nel",
                    "preferredName": "Mr Akujiobi, Nelson Sito",
                    "fullName": "Mr Akujiobi, Nelson Sito",
                    "emailAddress": "sito.mi.37@gmail.com",
                    "mobileNumber": "080111111111",
                    "membershipNumber": null,
                    "membershipStatus": "Non member",
                    "membershipType": null,
                    "contactStatus": 0,
                    "description": "<div>Student of the world. Learning at every chance</div>",
                    "externalIdentifier": null,
                    "importReference": null,
                    "birthDate": "2000-01-23T00:00:00.000000Z",
                    "dateRegistered": "2024-11-29T09:52:10.000000Z",
                    "dateJoined": null,
                    "createdAt": "2024-11-29T09:52:10.000000Z",
                    "updatedAt": "2024-11-29T09:52:17.000000Z",
                    "businessUnit": {
                        "id": 1,
                        "name": "Mobile App",
                        "parentId": null,
                        "description": null,
                        "groupId": 1,
                        "createdAt": "2024-11-28T16:29:31.000000Z",
                        "updatedAt": "2024-11-28T16:29:31.000000Z"
                    },
                    "contactCustom536": null
                },
                {
                    "id": 19,
                    "profilePictureUrl": null,
                    "firstName": "Nelson",
                    "surname": "Akujiobi",
                    "middleName": null,
                    "salutation": "Mr",
                    "postNominal": null,
                    "preferredName": "Mr Akujiobi, Nelson ",
                    "fullName": "Mr Akujiobi, Nelson ",
                    "emailAddress": "nelson135@toptech.co.uk",
                    "mobileNumber": null,
                    "membershipNumber": "5",
                    "membershipStatus": "Current",
                    "membershipType": {
                        "id": 1,
                        "name": "Associate Membership",
                        "description": "<div>Associate Membership</div>",
                        "customerType": "",
                        "displayOrder": 0,
                        "renewalType": "",
                        "renewalDay": 1,
                        "renewalMonth": 1,
                        "amount": "50.0000",
                        "productCode": "SB-1-1"
                    },
                    "contactStatus": 0,
                    "description": null,
                    "externalIdentifier": null,
                    "importReference": null,
                    "birthDate": null,
                    "dateRegistered": "2024-11-29T10:06:00.000000Z",
                    "dateJoined": "2024-11-29T00:00:00.000000Z",
                    "createdAt": "2024-11-29T10:06:00.000000Z",
                    "updatedAt": "2024-11-29T10:06:06.000000Z",
                    "businessUnit": {
                        "id": 6,
                        "name": "AYRSHIRE",
                        "parentId": 1,
                        "description": null,
                        "groupId": 2,
                        "createdAt": "2024-11-29T09:40:31.000000Z",
                        "updatedAt": "2024-11-29T09:40:31.000000Z"
                    },
                    "contactCustom536": null
                },
                {
                    "id": 31,
                    "profilePictureUrl": null,
                    "firstName": "Obi",
                    "surname": "Nwaneri",
                    "middleName": null,
                    "salutation": null,
                    "postNominal": null,
                    "preferredName": " Nwaneri, Obi ",
                    "fullName": " Nwaneri, Obi ",
                    "emailAddress": "obn@gmail.com",
                    "mobileNumber": null,
                    "membershipNumber": "740",
                    "membershipStatus": "Current",
                    "membershipType": {
                        "id": 4,
                        "name": "All Membership",
                        "description": "<div>All Membership</div>",
                        "customerType": "",
                        "displayOrder": 30,
                        "renewalType": "",
                        "renewalDay": 1,
                        "renewalMonth": 1,
                        "amount": "50.0000",
                        "productCode": "SB-1-4"
                    },
                    "contactStatus": 0,
                    "description": null,
                    "externalIdentifier": null,
                    "importReference": null,
                    "birthDate": null,
                    "dateRegistered": "2024-11-29T10:21:32.000000Z",
                    "dateJoined": "2024-11-29T00:00:00.000000Z",
                    "createdAt": "2024-11-29T10:21:32.000000Z",
                    "updatedAt": "2024-11-29T10:22:11.000000Z",
                    "businessUnit": {
                        "id": 1,
                        "name": "Mobile App",
                        "parentId": null,
                        "description": null,
                        "groupId": 1,
                        "createdAt": "2024-11-28T16:29:31.000000Z",
                        "updatedAt": "2024-11-28T16:29:31.000000Z"
                    },
                    "contactCustom536": null
                },
                {
                    "id": 6,
                    "profilePictureUrl": null,
                    "firstName": "Oli",
                    "surname": "Awaeka",
                    "middleName": null,
                    "salutation": "Mrs",
                    "postNominal": null,
                    "preferredName": "Mrs Awaeka, Oli ",
                    "fullName": "Mrs Awaeka, Oli ",
                    "emailAddress": "oawaeka@yopmail.com",
                    "mobileNumber": null,
                    "membershipNumber": "1",
                    "membershipStatus": "Current",
                    "membershipType": {
                        "id": 1,
                        "name": "Associate Membership",
                        "description": "<div>Associate Membership</div>",
                        "customerType": "",
                        "displayOrder": 0,
                        "renewalType": "",
                        "renewalDay": 1,
                        "renewalMonth": 1,
                        "amount": "50.0000",
                        "productCode": "SB-1-1"
                    },
                    "contactStatus": 0,
                    "description": null,
                    "externalIdentifier": null,
                    "importReference": null,
                    "birthDate": null,
                    "dateRegistered": "2024-11-29T09:48:21.000000Z",
                    "dateJoined": "2024-11-29T00:00:00.000000Z",
                    "createdAt": "2024-11-29T09:48:21.000000Z",
                    "updatedAt": "2024-11-29T09:48:36.000000Z",
                    "businessUnit": {
                        "id": 1,
                        "name": "Mobile App",
                        "parentId": null,
                        "description": null,
                        "groupId": 1,
                        "createdAt": "2024-11-28T16:29:31.000000Z",
                        "updatedAt": "2024-11-28T16:29:31.000000Z"
                    },
                    "contactCustom536": null
                },
                {
                    "id": 7,
                    "profilePictureUrl": null,
                    "firstName": "Oli",
                    "surname": "Awaeka",
                    "middleName": null,
                    "salutation": "Mrs",
                    "postNominal": null,
                    "preferredName": "Mrs Awaeka, Oli ",
                    "fullName": "Mrs Awaeka, Oli ",
                    "emailAddress": "oawaeka@yopmail.com",
                    "mobileNumber": null,
                    "membershipNumber": "2",
                    "membershipStatus": "Current",
                    "membershipType": {
                        "id": 1,
                        "name": "Associate Membership",
                        "description": "<div>Associate Membership</div>",
                        "customerType": "",
                        "displayOrder": 0,
                        "renewalType": "",
                        "renewalDay": 1,
                        "renewalMonth": 1,
                        "amount": "50.0000",
                        "productCode": "SB-1-1"
                    },
                    "contactStatus": 0,
                    "description": null,
                    "externalIdentifier": null,
                    "importReference": null,
                    "birthDate": null,
                    "dateRegistered": "2024-11-29T09:49:12.000000Z",
                    "dateJoined": "2024-11-29T00:00:00.000000Z",
                    "createdAt": "2024-11-29T09:49:12.000000Z",
                    "updatedAt": "2024-11-29T09:49:18.000000Z",
                    "businessUnit": {
                        "id": 1,
                        "name": "Mobile App",
                        "parentId": null,
                        "description": null,
                        "groupId": 1,
                        "createdAt": "2024-11-28T16:29:31.000000Z",
                        "updatedAt": "2024-11-28T16:29:31.000000Z"
                    },
                    "contactCustom536": null
                },
                {
                    "id": 28,
                    "profilePictureUrl": null,
                    "firstName": "Oluchi",
                    "surname": "Onyekachi",
                    "middleName": null,
                    "salutation": null,
                    "postNominal": null,
                    "preferredName": " Onyekachi, Oluchi ",
                    "fullName": " Onyekachi, Oluchi ",
                    "emailAddress": "olu@gmail.com",
                    "mobileNumber": null,
                    "membershipNumber": "736",
                    "membershipStatus": "Current",
                    "membershipType": {
                        "id": 1,
                        "name": "Associate Membership",
                        "description": "<div>Associate Membership</div>",
                        "customerType": "",
                        "displayOrder": 0,
                        "renewalType": "",
                        "renewalDay": 1,
                        "renewalMonth": 1,
                        "amount": "50.0000",
                        "productCode": "SB-1-1"
                    },
                    "contactStatus": 0,
                    "description": null,
                    "externalIdentifier": null,
                    "importReference": null,
                    "birthDate": null,
                    "dateRegistered": "2024-11-29T10:17:44.000000Z",
                    "dateJoined": "2024-11-29T00:00:00.000000Z",
                    "createdAt": "2024-11-29T10:17:44.000000Z",
                    "updatedAt": "2024-11-29T10:17:49.000000Z",
                    "businessUnit": {
                        "id": 1,
                        "name": "Mobile App",
                        "parentId": null,
                        "description": null,
                        "groupId": 1,
                        "createdAt": "2024-11-28T16:29:31.000000Z",
                        "updatedAt": "2024-11-28T16:29:31.000000Z"
                    },
                    "contactCustom536": null
                },
                {
                    "id": 13,
                    "profilePictureUrl": null,
                    "firstName": "Paul",
                    "surname": "Coll",
                    "middleName": "Blatt",
                    "salutation": "Mr",
                    "postNominal": null,
                    "preferredName": "Mr Coll, Paul Blatt",
                    "fullName": "Mr Coll, Paul Blatt",
                    "emailAddress": "Pauli@gmail.com",
                    "mobileNumber": null,
                    "membershipNumber": null,
                    "membershipStatus": "Non member",
                    "membershipType": null,
                    "contactStatus": 0,
                    "description": null,
                    "externalIdentifier": null,
                    "importReference": null,
                    "birthDate": null,
                    "dateRegistered": "2024-11-29T09:53:39.000000Z",
                    "dateJoined": null,
                    "createdAt": "2024-11-29T09:53:39.000000Z",
                    "updatedAt": "2024-11-29T09:53:42.000000Z",
                    "businessUnit": {
                        "id": 1,
                        "name": "Mobile App",
                        "parentId": null,
                        "description": null,
                        "groupId": 1,
                        "createdAt": "2024-11-28T16:29:31.000000Z",
                        "updatedAt": "2024-11-28T16:29:31.000000Z"
                    },
                    "contactCustom536": null
                },
                {
                    "id": 29,
                    "profilePictureUrl": null,
                    "firstName": "Ratha",
                    "surname": "Sabastien",
                    "middleName": null,
                    "salutation": null,
                    "postNominal": null,
                    "preferredName": " Sabastien, Ratha ",
                    "fullName": " Sabastien, Ratha ",
                    "emailAddress": "rath@gmail.com",
                    "mobileNumber": null,
                    "membershipNumber": "738",
                    "membershipStatus": "Current",
                    "membershipType": {
                        "id": 1,
                        "name": "Associate Membership",
                        "description": "<div>Associate Membership</div>",
                        "customerType": "",
                        "displayOrder": 0,
                        "renewalType": "",
                        "renewalDay": 1,
                        "renewalMonth": 1,
                        "amount": "50.0000",
                        "productCode": "SB-1-1"
                    },
                    "contactStatus": 0,
                    "description": null,
                    "externalIdentifier": null,
                    "importReference": null,
                    "birthDate": null,
                    "dateRegistered": "2024-11-29T10:18:48.000000Z",
                    "dateJoined": "2024-11-29T00:00:00.000000Z",
                    "createdAt": "2024-11-29T10:18:48.000000Z",
                    "updatedAt": "2024-11-29T10:18:59.000000Z",
                    "businessUnit": {
                        "id": 1,
                        "name": "Mobile App",
                        "parentId": null,
                        "description": null,
                        "groupId": 1,
                        "createdAt": "2024-11-28T16:29:31.000000Z",
                        "updatedAt": "2024-11-28T16:29:31.000000Z"
                    },
                    "contactCustom536": null
                },
                {
                    "id": 4,
                    "profilePictureUrl": null,
                    "firstName": "Ronaldo",
                    "surname": "Daugherty",
                    "middleName": null,
                    "salutation": null,
                    "postNominal": null,
                    "preferredName": " Daugherty, Ronaldo ",
                    "fullName": " Daugherty, Ronaldo ",
                    "emailAddress": "Jamaal_Feeney91@yahoo.com",
                    "mobileNumber": "(235) 604-6788 x27631",
                    "membershipNumber": null,
                    "membershipStatus": "Non member",
                    "membershipType": null,
                    "contactStatus": 0,
                    "description": null,
                    "externalIdentifier": null,
                    "importReference": null,
                    "birthDate": null,
                    "dateRegistered": "2024-11-29T09:44:36.000000Z",
                    "dateJoined": null,
                    "createdAt": "2024-11-29T09:44:36.000000Z",
                    "updatedAt": "2024-11-29T09:44:36.000000Z",
                    "businessUnit": {
                        "id": 1,
                        "name": "Mobile App",
                        "parentId": null,
                        "description": null,
                        "groupId": 1,
                        "createdAt": "2024-11-28T16:29:31.000000Z",
                        "updatedAt": "2024-11-28T16:29:31.000000Z"
                    },
                    "contactCustom536": null
                },
                {
                    "id": 3,
                    "profilePictureUrl": null,
                    "firstName": "Shanon",
                    "surname": "Goldner",
                    "middleName": null,
                    "salutation": null,
                    "postNominal": null,
                    "preferredName": " Goldner, Shanon ",
                    "fullName": " Goldner, Shanon ",
                    "emailAddress": "Korey63@gmail.com",
                    "mobileNumber": "1-872-497-0784 x7341",
                    "membershipNumber": null,
                    "membershipStatus": "Non member",
                    "membershipType": null,
                    "contactStatus": 0,
                    "description": null,
                    "externalIdentifier": null,
                    "importReference": null,
                    "birthDate": null,
                    "dateRegistered": "2024-11-29T09:43:50.000000Z",
                    "dateJoined": null,
                    "createdAt": "2024-11-29T09:43:50.000000Z",
                    "updatedAt": "2024-11-29T09:43:50.000000Z",
                    "businessUnit": {
                        "id": 1,
                        "name": "Mobile App",
                        "parentId": null,
                        "description": null,
                        "groupId": 1,
                        "createdAt": "2024-11-28T16:29:31.000000Z",
                        "updatedAt": "2024-11-28T16:29:31.000000Z"
                    },
                    "contactCustom536": null
                },
                {
                    "id": 18,
                    "profilePictureUrl": null,
                    "firstName": "Sony",
                    "surname": "Bill",
                    "middleName": null,
                    "salutation": null,
                    "postNominal": null,
                    "preferredName": " Bill, Sony ",
                    "fullName": " Bill, Sony ",
                    "emailAddress": "bill.sony@yopmail.com",
                    "mobileNumber": null,
                    "membershipNumber": null,
                    "membershipStatus": "Non member",
                    "membershipType": null,
                    "contactStatus": 0,
                    "description": null,
                    "externalIdentifier": null,
                    "importReference": null,
                    "birthDate": null,
                    "dateRegistered": "2024-11-29T10:05:09.000000Z",
                    "dateJoined": null,
                    "createdAt": "2024-11-29T10:05:09.000000Z",
                    "updatedAt": "2024-11-29T10:05:09.000000Z",
                    "businessUnit": {
                        "id": 1,
                        "name": "Mobile App",
                        "parentId": null,
                        "description": null,
                        "groupId": 1,
                        "createdAt": "2024-11-28T16:29:31.000000Z",
                        "updatedAt": "2024-11-28T16:29:31.000000Z"
                    },
                    "contactCustom536": null
                },
                {
                    "id": 26,
                    "profilePictureUrl": null,
                    "firstName": "Stan",
                    "surname": "Agada",
                    "middleName": null,
                    "salutation": "Mx",
                    "postNominal": null,
                    "preferredName": "Mx Agada, Stan ",
                    "fullName": "Mx Agada, Stan ",
                    "emailAddress": "agada@gmail.com",
                    "mobileNumber": null,
                    "membershipNumber": "10",
                    "membershipStatus": "Current",
                    "membershipType": {
                        "id": 7,
                        "name": "Contact Membership 535",
                        "description": "<div>Contact Membershiper</div>",
                        "customerType": "",
                        "displayOrder": 60,
                        "renewalType": "",
                        "renewalDay": 1,
                        "renewalMonth": 1,
                        "amount": "43.0000",
                        "productCode": "SB-1-9"
                    },
                    "contactStatus": 0,
                    "description": null,
                    "externalIdentifier": null,
                    "importReference": null,
                    "birthDate": null,
                    "dateRegistered": "2024-11-29T10:16:31.000000Z",
                    "dateJoined": "2024-11-29T00:00:00.000000Z",
                    "createdAt": "2024-11-29T10:16:31.000000Z",
                    "updatedAt": "2024-11-29T10:16:35.000000Z",
                    "businessUnit": {
                        "id": 1,
                        "name": "Mobile App",
                        "parentId": null,
                        "description": null,
                        "groupId": 1,
                        "createdAt": "2024-11-28T16:29:31.000000Z",
                        "updatedAt": "2024-11-28T16:29:31.000000Z"
                    },
                    "contactCustom536": null
                },
                {
                    "id": 14,
                    "profilePictureUrl": null,
                    "firstName": "Tom",
                    "surname": "Coll",
                    "middleName": "Cruise",
                    "salutation": "Mr",
                    "postNominal": null,
                    "preferredName": "Mr Coll, Tom Cruise",
                    "fullName": "Mr Coll, Tom Cruise",
                    "emailAddress": "tom@gmail.com",
                    "mobileNumber": null,
                    "membershipNumber": null,
                    "membershipStatus": "Non member",
                    "membershipType": null,
                    "contactStatus": 0,
                    "description": null,
                    "externalIdentifier": null,
                    "importReference": null,
                    "birthDate": null,
                    "dateRegistered": "2024-11-29T09:54:07.000000Z",
                    "dateJoined": null,
                    "createdAt": "2024-11-29T09:54:07.000000Z",
                    "updatedAt": "2024-11-29T09:54:16.000000Z",
                    "businessUnit": {
                        "id": 1,
                        "name": "Mobile App",
                        "parentId": null,
                        "description": null,
                        "groupId": 1,
                        "createdAt": "2024-11-28T16:29:31.000000Z",
                        "updatedAt": "2024-11-28T16:29:31.000000Z"
                    },
                    "contactCustom536": null
                },
                {
                    "id": 23,
                    "profilePictureUrl": null,
                    "firstName": "Tony",
                    "surname": "Stark",
                    "middleName": null,
                    "salutation": null,
                    "postNominal": null,
                    "preferredName": " Stark, Tony ",
                    "fullName": " Stark, Tony ",
                    "emailAddress": "tony.stark@hotmail.com",
                    "mobileNumber": null,
                    "membershipNumber": null,
                    "membershipStatus": "Non member",
                    "membershipType": null,
                    "contactStatus": 0,
                    "description": null,
                    "externalIdentifier": null,
                    "importReference": null,
                    "birthDate": null,
                    "dateRegistered": "2024-11-29T10:11:58.000000Z",
                    "dateJoined": null,
                    "createdAt": "2024-11-29T10:11:58.000000Z",
                    "updatedAt": "2024-11-29T10:11:58.000000Z",
                    "businessUnit": {
                        "id": 1,
                        "name": "Mobile App",
                        "parentId": null,
                        "description": null,
                        "groupId": 1,
                        "createdAt": "2024-11-28T16:29:31.000000Z",
                        "updatedAt": "2024-11-28T16:29:31.000000Z"
                    },
                    "contactCustom536": null
                }
            ],
            "links": {
                "first": "https://ma.memberbase-test.com/api/v1/contacts?page=1",
                "last": "https://ma.memberbase-test.com/api/v1/contacts?page=1",
                "prev": null,
                "next": null
            },
            "meta": {
                "current_page": 1,
                "from": 1,
                "last_page": 1,
                "links": [
                    {
                        "url": null,
                        "label": "pagination.previous",
                        "active": false
                    },
                    {
                        "url": "https://ma.memberbase-test.com/api/v1/contacts?page=1",
                        "label": "1",
                        "active": true
                    },
                    {
                        "url": null,
                        "label": "pagination.next",
                        "active": false
                    }
                ],
                "path": "https://ma.memberbase-test.com/api/v1/contacts",
                "per_page": 30,
                "to": 30,
                "total": 30
            }
        }

        return NextResponse.json(data);
    } catch (error) {
        return NextResponse.json(
            { error: (error as Error).message || "An unexpected error occurred" },
            { status: 500 }
        );
    }
}

export async function PUT() {
    try {
        const data = {
            "message": "Contact edited",
            "status": "success"
        }

        return NextResponse.json(data);
    } catch (error) {
        return NextResponse.json(
            { error: (error as Error).message || "An unexpected error occurred" },
            { status: 500 }
        );
    }
}
